language: objective-c
osx_image: xcode11.3

script:
  - xctool -workspace FFTravis.xcworkspace -scheme FFTravis -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace FFTravis.xcworkspace -scheme FFTravisTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

after_success:
- bash <(curl -s https://codecov.io/bash)
